import continued_fractions_complex_analytic_aspects_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace continued_fractions_complex_analytic_aspects_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end continued_fractions_complex_analytic_aspects_theorem_canonical_lane_mathlib
end HautevilleHouse
